#
# Executes commands at login pre-zshrc.
#

#
# Aliases
#

alias vi="vim"
alias v="fasd -f -e vim"

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vi'
export VISUAL='vi'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#


# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/.pub-cache/bin
  $HOME/.node/bin
  $GOPATH/bin
  $path
)

# Set the list of directories that Zsh searches for manuals
MANPATH="$(manpath)"
manpath=(
  $(brew --prefix coreutils)/libexec/gnubin
  $manpath
)

# Add Homebrew to completion path
fpath=(
  /usr/local/bin
  $fpath
)

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path manpath
export PATH
export MANPATH
export FPATH

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
