#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load custom aliases
if [[ -d "${ZDOTDIR:-$HOME}/.zprezto/aliases" ]]; then
  for file in "${ZDOTDIR:-$HOME}"/.zprezto/aliases/*.zsh; do
    source "$file"
  done
fi

# Pipe to multiple outputs
setopt MULTIOS

# Make cd=pushd
setopt AUTO_PUSHD

# This will use named dirs when possible
setopt AUTO_NAME_DIRS

# If we have a glob this will expand it
setopt GLOB_COMPLETE

# Blank pushd goes to home
setopt PUSHD_TO_HOME

# Ignore multiple directories for the stack
setopt PUSHD_IGNORE_DUPS

# Disable Ctrl-s
setopt NO_FLOW_CONTROL

# Prevent clobbering
setopt NO_CLOBBER

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be reasonable!
setopt NUMERIC_GLOB_SORT

# Extended glob
setopt EXTENDED_GLOB

bindkey -M viins ' ' magic-space

bindkey '^P' up-line-or-search
bindkey '^N' down-line-or-search
